version: "3.8"
services:
    database:
        image: mysql:8
        ports:
            - 3306:3306
        networks:
            - manatee
        volumes:
            - database_data:/var/lib/mysql
            - ./data:/mnt/host:ro
        environment: 
            - MYSQL_ROOT_PASSWORD=RosewoodSilverSpoon
    server:
        build: ./server
        ports:
            - 8080:8080
        networks:
            - manatee
        depends_on: 
            - database
    web:
        build: ./web-client
        ports:
            - 80:80
        networks:
            - manatee
        depends_on: 
            - server

networks:
    manatee:

volumes:
    database_data: